services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/dist
    environment:
      - VITE_ALLOWED_HOSTS=localhost
      - VITE_SERVER_ORIGIN=http://localhost:4321
      - VITE_PORT=4321
    ports:
      - "4321:4321"